spring:
  profile:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/adrielcardoso/netflixoss-config.git/
          search-paths:
              - "EmailServiceConfigProperties/{application}/{profile}"